image: docker

services:
  - docker:dind

stages:
  - build

docker-test:
  stage: build
  script:
      - apk add --no-cache docker-compose
      - docker-compose -f docker-compose_tests.yaml up
      - docker-compose -f docker-compose_tests.yaml exec tests python -m pytest