image: docker

services:
  - docker:dind

stages:
  - build

docker-test:
  stage: build
  script:
      - apk add --no-cache docker-compose
      - docker-compose -f docker-compose_tests up
      - time sleep 5
      - docker-compose -f docker-compose_tests exec tests python -m pytest