#!/usr/bin/python
import re
import sys

msg = sys.argv[1]
pattern = '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\(([\w\-.]+)\))?(!)?: ([\w ])+([\s\S]*)'

with open (msg, 'r') as f: 
	content = f.read()
	if re.search(pattern, content):
		print("Changes commited properly")
		sys.exit(0)
	else:
		print("Bad commit name, check your commit with begining: build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test ")
		sys.exit(1)