#!/usr/bin/python

print("[INFO]")
print("U will be thrown to a commitinng window in a while.")
print("Begin your commit message with one of the following topics:")
print("build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test")